# Generated by Django 5.1 on 2024-10-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_remove_ticket_support_role_delete_supportrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="assigned_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("commercial", "Commercial"),
                    ("technical_support", "Technical Support"),
                    ("legal_support", "Legal Support"),
                    ("second_line_support", "2nd Line Support"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
